version: '3'
services:
  safeplaces:
    build:
      context: .
      # dockerfile: Dockerfile
      # image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- /home/node/app/node_modules/.bin/nodemon app.js 

  db:
    image: postgres:12.2
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
  node_modules:  
